### ISSUE TITLE
bug: create_context_from_masking() iterates through chromosome_lengths incorrectly

### ISSUE THREAD

**Issue by biermanr** [fmfi-compbio/mcdp2#1]
Hi, Thank you for this nice program

I ran into a small bug when I was running mcdp2 with a mask in "single" mode.

The error is that the chromosome_lengths are trying to be iterated through as a dictionary, but chromosome_lengths is a list of tuples. You can see I made a small change, which fixed the error for me in the mcdp2/common/io.py file
```
335     #RB editing to avoid "ERROR list has no attribute items"
336     #for c, l in chromosome_lengths.items():
337     for c, l in chromosome_lengths:
338         events.append((c, 0, Event.CBEGIN))
339         events.append((c, l, Event.CEND))
```

The create_default_context function treats the chromosome_lengths correctly, this is just an issue when using the masking.
```
 71 def create_default_context(chromosome_lengths, separate_models=False):
 72     result = {}
 73     for name, length in chromosome_lengths:
 74         if separate_models:
 75             result[name] = [(name, 0, length)]
 76         else:
 77             result[name] = [("g", 0, length)]
 78     return result
```

**Comment by biermanr** [comment]
There was another problem a few lines down caused again by `chromosome_lengths` being a list of tuples instead of a dict

```
    #result = {c: [] for c in chromosome_lengths}
    result = {c: [] for c,l in chromosome_lengths}
```

**Comment by japdlsd** [comment]
Thanks for the feedback! I'll look into it as soon as possible :)

**Comment by japdlsd** [comment]
Thanks again, I've added your fixes to the code (It took me a while, but the last couple of weeks were a nightmare).
